#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 16 09:54:01 2017

@author: pohno
"""

path = '/Users/pohno/Box Sync/Science/Experimental/Software/SFGprocessing/Python/example'

from spectrum import Spectrum

a = Spectrum(path)